### ISSUE TITLE
How is `streamsx.standard.files.csv_reader` meant to be used?

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.standard#24]
The `file` parameter is hardcoded, but for that to work the path to the file on the Streams host must be known at job submission time.

This code:
```
import streamsx.ec
from  streamsx.standard.files import csv_reader

from streamsx.topology.topology import Topology
import streamsx.topology.context

csv_file_name = "next_bus_avg_max_speed.csv"    

csvtopo = Topology()

csv_schema = 'tuple<int64 last_seen, float32 maxSpeed, rstring id, float32 avgSpeed>'
file = "etc/" + csv_file_name
readings = csv_reader(csvtopo, file="/Users/natashad/Downloads/next_bus_avg_max_speed.csv", schema=csv_schema, header=True, name="ReadCSV")
readings.print()
```
Throws a FileNotFound error.

**Comment by ddebrunner** [comment]
Where are you expecting the csv file to be located?

**Comment by natashadsilva** [comment]
Is the operator not supported if the CSV file isn't on the same host as Streams? How would I use it from a notebook in Watson Studio, for example?

**Comment by markheger** [comment]
csv_reader handles files with relative path as file relative to applicationDir, expects that files are added to the bundle with `topology.add_file_dependency`
documentation updated and examples added
