### ISSUE TITLE
convert csv_reader/writer to composite classes

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.standard#41]

**Comment by ddebrunner** [comment]
The reader wants to be include a scanning directory option as well as a single file.

**Comment by markheger** [comment]
Current 0.9 version contains 
* DirectoryScan(source)
* CSVReader(source) for single file
* CSVFilesReader(map) for multiple files

Combining both "Readers" into one would be possible.

```
scanned = topo.source(files.DirectoryScan(directory=dir))
r = scanned.map(files.CSVFilesReader(), schema=StreamSchema('tuple<rstring a, int32 b>'))
```

**Comment by ddebrunner** [comment]
@markheger Maybe a `CSVDirectoryScan` ??

**Comment by markheger** [comment]
having the FileSource and DirScan separated has advantages in doing parallel reads, UDP or ThreadedSplit for the FileSources
